# Generated by Django 5.2.15 on 2026-09-19 21:49

import apps.core.crypto
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('cni', 'CNI'), ('photo', 'Photo'), ('medical', 'Certificat médical'), ('admin', 'Justificatif administratif'), ('payment', 'Justificatif de paiement'), ('exam', "Document d'examen"), ('certificate', 'Certificat de réussite'), ('other', 'Autre')], max_length=15)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('file', models.FileField(upload_to='learners/docs/')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matricule', models.CharField(blank=True, max_length=40)),
                ('employee_ref', models.CharField(blank=True, max_length=60, verbose_name='Matricule employeur/établissement')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='learners/photos/')),
                ('id_document_no', apps.core.crypto.EncryptedCharField(blank=True, max_length=255, verbose_name="N° pièce d'identité")),
                ('category', models.CharField(choices=[('A', 'Permis A'), ('A1', 'Permis A1'), ('B', 'Permis B'), ('C', 'Permis C'), ('D', 'Permis D'), ('E', 'Permis E'), ('OTHER', 'Autre')], default='B', max_length=10)),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('registered', 'Inscrit'), ('in_training', 'Formation en cours'), ('training_done', 'Formation terminée'), ('exam_scheduled', 'Examen programmé'), ('passed', 'Admis'), ('failed', 'Échec'), ('licensed', 'Permis obtenu'), ('dropped', 'Abandonné')], default='new', max_length=20)),
                ('source', models.CharField(choices=[('secretary', 'Secrétaire'), ('online', 'En ligne'), ('organization', 'Organisation')], default='secretary', max_length=15)),
                ('registered_at', models.DateField(default=django.utils.timezone.localdate)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learners', to='schools.agency')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
