# Generated by Django 5.2.15 on 2026-09-19 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learners', '0001_initial'),
        ('organizations', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learners', to='organizations.cohort'),
        ),
        migrations.AddField(
            model_name='learner',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learners', to='organizations.group'),
        ),
        migrations.AddField(
            model_name='learner',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learners', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='learner',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learners', to='schools.school'),
        ),
        migrations.AddField(
            model_name='learner',
            name='training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learners', to='schools.training'),
        ),
        migrations.AddField(
            model_name='learner',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learner_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learnerdocument',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='learners.learner'),
        ),
        migrations.AddField(
            model_name='learnerdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='learner',
            constraint=models.UniqueConstraint(fields=('school', 'matricule'), name='uniq_matricule_per_school'),
        ),
    ]
