# Generated by Django 5.2.15 on 2026-09-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='license_obtained_at',
            field=models.DateField(blank=True, help_text='Renseignée automatiquement au passage du statut à « Permis obtenu » ; sert de point de départ aux relances de recyclage.', null=True, verbose_name="Date d'obtention du permis"),
        ),
    ]
