# Generated by Django 5.2.15 on 2026-09-26 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
        ('learners', '0003_learner_license_obtained_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='approval_reject_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learner',
            name='approval_status',
            field=models.CharField(choices=[('pending', "En attente d'approbation"), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], default='approved', max_length=10),
        ),
        migrations.AddField(
            model_name='learner',
            name='id_document_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='learner',
            name='org_sequence_no',
            field=models.PositiveIntegerField(blank=True, help_text='Calculé automatiquement au sein de la collectivité rattachée (ex. INSAAC).', null=True, verbose_name="Numéro d'ordre (collectivité)"),
        ),
        migrations.AddField(
            model_name='learner',
            name='quote',
            field=models.ForeignKey(blank=True, help_text="Devis individuel à l'origine de cette inscription, le cas échéant.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learners', to='admissions.individualquote'),
        ),
        migrations.AddField(
            model_name='learner',
            name='zone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Zone géographique déclarée'),
        ),
    ]
