# Generated by Django 5.2.15 on 2026-09-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0004_learner_approval_reject_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='engagement_downloaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Fiche d'engagement téléchargée le"),
        ),
        migrations.AlterField(
            model_name='learnerdocument',
            name='doc_type',
            field=models.CharField(choices=[('cni', 'CNI'), ('photo', 'Photo'), ('medical', 'Certificat médical'), ('admin', 'Justificatif administratif'), ('payment', 'Justificatif de paiement'), ('engagement', "Fiche d'engagement signée"), ('exam', "Document d'examen"), ('certificate', 'Certificat de réussite'), ('other', 'Autre')], max_length=15),
        ),
    ]
