# Generated by Django 5.2.15 on 2026-09-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0005_learner_engagement_downloaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='engagement_paper_received_at',
            field=models.DateField(blank=True, null=True, verbose_name="Fiche d'engagement remise en version papier le"),
        ),
    ]
