# Generated by Django 5.2.15 on 2026-09-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='voice_enabled',
            field=models.BooleanField(default=False, verbose_name='Connexion vocale activée'),
        ),
        migrations.AddField(
            model_name='user',
            name='voice_pin_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
