# Generated by Django 5.2.15 on 2026-09-20 01:17

from django.db import migrations, models


def backfill(apps, schema_editor):
    from apps.accounts.models import normalize_phone
    User = apps.get_model("accounts", "User")
    for u in User.objects.exclude(phone=""):
        User.objects.filter(pk=u.pk).update(phone_norm=normalize_phone(u.phone))


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_voice_enabled_user_voice_pin_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_norm',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=10),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]