# Generated by Django 5.2.15 on 2026-09-19 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('due_date', models.DateField()),
                ('paid_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
            ],
            options={
                'ordering': ['invoice', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('quote', 'Devis'), ('invoice', 'Facture'), ('credit_note', 'Avoir')], default='invoice', max_length=12)),
                ('number', models.CharField(blank=True, max_length=40)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('paid', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('issued', 'Émise'), ('partial', 'Partiellement payée'), ('paid', 'Payée'), ('cancelled', 'Annulée')], default='issued', max_length=12)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('unit_price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('orange_money', 'Orange Money'), ('mtn_momo', 'MTN MoMo'), ('moov_money', 'Moov Money'), ('wave', 'Wave'), ('cash', 'Espèces'), ('transfer', 'Virement'), ('card', 'Carte bancaire'), ('other', 'Autre')], max_length=15)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('failed', 'Échoué')], default='pending', max_length=10)),
                ('payer_phone', models.CharField(blank=True, max_length=30)),
                ('provider_ref', models.CharField(blank=True, db_index=True, max_length=100)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('receipt_number', models.CharField(blank=True, max_length=40)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('salary', 'Salaires'), ('commission', 'Commissions'), ('fuel', 'Carburant'), ('maintenance', 'Maintenance'), ('rent', 'Loyers'), ('supplies', 'Fournitures'), ('communication', 'Communication'), ('other', 'Autres charges')], max_length=15)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='schools.agency')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
