# Generated by Django 5.2.15 on 2026-09-20 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('orange_money', 'Orange Money'), ('mtn_momo', 'MTN MoMo'), ('moov_money', 'Moov Money'), ('wave', 'Wave'), ('cinetpay', 'CinetPay (Mobile Money / Carte)'), ('cash', 'Espèces'), ('transfer', 'Virement'), ('card', 'Carte bancaire'), ('other', 'Autre')], max_length=15),
        ),
    ]
