# Generated by Django 5.2.15 on 2026-09-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='payments/receipts/', verbose_name='Reçu / justificatif signé'),
        ),
    ]
