# Generated by Django 5.2.15 on 2026-09-26 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('schools', '0006_school_covered_zones'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(choices=[('registration', 'Inscription reçue (accusé au candidat)'), ('registration_pending', 'Nouvelle inscription à approuver (secrétariat)'), ('registration_approved', 'Inscription approuvée (candidat)'), ('individual_quote', 'Nouvelle demande de devis individuel (secrétariat)'), ('quote_request', 'Nouvelle demande de devis entreprise (secrétariat)'), ('recycling_reminder', 'Relance recyclage (candidat)'), ('new_lesson', 'Nouvelle séance programmée'), ('planning_change', 'Changement de planning'), ('result', 'Résultat de QCM'), ('exam_result', "Résultat d'examen"), ('certificate_ready', 'Certificat disponible'), ('payment_confirmed', 'Paiement confirmé'), ('schedule_settled', 'Facture soldée'), ('installment_due_soon', "Rappel d'échéance à venir"), ('installment_late', 'Échéance en retard'), ('subscription_active', 'Abonnement activé'), ('subscription_failed', "Échec de paiement d'abonnement"), ('subscription_expiring', 'Abonnement bientôt expiré'), ('subscription_suspended', 'Abonnement suspendu'), ('verification', 'Code de vérification')], max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('channels', models.JSONField(blank=True, default=list, help_text='["inapp", "email", "sms", "whatsapp", "push"]')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_settings', to='schools.school')),
            ],
            options={
                'ordering': ['event'],
                'constraints': [models.UniqueConstraint(fields=('school', 'event'), name='uniq_alert_setting_school_event')],
            },
        ),
    ]
