# Generated by Django 5.2.15 on 2026-09-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alertsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertsetting',
            name='event',
            field=models.CharField(choices=[('registration', 'Inscription reçue (accusé au candidat)'), ('registration_pending', 'Nouvelle inscription à approuver (secrétariat)'), ('registration_approved', 'Inscription approuvée (candidat)'), ('registration_rejected', 'Inscription refusée, avec le motif (candidat)'), ('quote_rejected', 'Demande de devis rejetée, avec le motif (candidat)'), ('quote_correction', 'Demande de devis à corriger (candidat)'), ('individual_quote', 'Nouvelle demande de devis individuel (secrétariat)'), ('quote_request', 'Nouvelle demande de devis entreprise (secrétariat)'), ('recycling_reminder', 'Relance recyclage (candidat)'), ('new_lesson', 'Nouvelle séance programmée'), ('planning_change', 'Changement de planning'), ('result', 'Résultat de QCM'), ('exam_result', "Résultat d'examen"), ('certificate_ready', 'Certificat disponible'), ('payment_confirmed', 'Paiement confirmé'), ('schedule_settled', 'Facture soldée'), ('installment_due_soon', "Rappel d'échéance à venir"), ('installment_late', 'Échéance en retard'), ('subscription_active', 'Abonnement activé'), ('subscription_failed', "Échec de paiement d'abonnement"), ('subscription_expiring', 'Abonnement bientôt expiré'), ('subscription_suspended', 'Abonnement suspendu'), ('verification', 'Code de vérification')], max_length=40),
        ),
    ]
