# Generated by Django 5.2.15 on 2026-09-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_alertsetting_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertsetting',
            name='body',
            field=models.TextField(blank=True, help_text='Variables : {titre} {message} {nom}. Vide = texte par défaut.', verbose_name='Message personnalisé'),
        ),
        migrations.AddField(
            model_name='alertsetting',
            name='subject',
            field=models.CharField(blank=True, help_text='Variables : {titre} {message} {nom}. Vide = texte par défaut.', max_length=200, verbose_name='Objet / titre personnalisé'),
        ),
    ]
