# Generated by Django 5.2.15 on 2026-09-19 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learners', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('in_progress', 'En cours'), ('finished', 'Terminée'), ('expired', 'Expirée')], default='in_progress', max_length=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('wrong_count', models.PositiveIntegerField(default=0)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('max_score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('passed', models.BooleanField(default=False)),
                ('is_exam', models.BooleanField(default=False)),
                ('threshold', models.PositiveSmallIntegerField(default=70)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learners.learner')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='schools.school')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('theory', 'Théorique'), ('practical', 'Pratique')], default='theory', max_length=10)),
                ('theme', models.CharField(choices=[('code', 'Code de la route'), ('signs', 'Signalisation'), ('priority', 'Priorités'), ('safety', 'Sécurité routière'), ('regulation', 'Réglementation'), ('mechanics', 'Mécanique'), ('behavior', 'Comportement du conducteur'), ('defensive', 'Conduite préventive'), ('firstaid', 'Premiers secours'), ('other', 'Autre')], default='code', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='schools.school')),
                ('training', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='schools.training')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material_type', models.CharField(choices=[('text', 'Texte'), ('image', 'Image'), ('pdf', 'PDF'), ('video', 'Vidéo'), ('other', 'Autre')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='courses/')),
                ('url', models.URLField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='pedagogy.course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=255)),
                ('dry_run', models.BooleanField(default=True)),
                ('total', models.PositiveIntegerField(default=0)),
                ('valid', models.PositiveIntegerField(default=0)),
                ('imported', models.PositiveIntegerField(default=0)),
                ('duplicates', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(default=list)),
                ('preview', models.JSONField(default=list)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='schools.school')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=60)),
                ('category', models.CharField(choices=[('A', 'Permis A'), ('A1', 'Permis A1'), ('B', 'Permis B'), ('C', 'Permis C'), ('D', 'Permis D'), ('E', 'Permis E'), ('OTHER', 'Autre')], default='B', max_length=10)),
                ('theme', models.CharField(choices=[('code', 'Code de la route'), ('signs', 'Signalisation'), ('priority', 'Priorités'), ('safety', 'Sécurité routière'), ('regulation', 'Réglementation'), ('mechanics', 'Mécanique'), ('behavior', 'Comportement du conducteur'), ('defensive', 'Conduite préventive'), ('firstaid', 'Premiers secours'), ('other', 'Autre')], default='code', max_length=20)),
                ('subtheme', models.CharField(blank=True, max_length=100)),
                ('difficulty', models.CharField(choices=[('easy', 'Facile'), ('medium', 'Moyen'), ('hard', 'Difficile')], default='medium', max_length=10)),
                ('qtype', models.CharField(choices=[('tf', 'Vrai/Faux'), ('single', 'Réponse unique'), ('multi', 'Choix multiple')], default='single', max_length=10)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('explanation', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(blank=True, help_text='Vide = banque centrale Akwaba, visible de toutes les auto-écoles', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='schools.school')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='A, B, C, D / Vrai, Faux', max_length=5)),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='pedagogy.question')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('selected', models.JSONField(blank=True, default=list)),
                ('answered', models.BooleanField(default=False)),
                ('is_correct', models.BooleanField(default=False)),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='pedagogy.attempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pedagogy.question')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('A', 'Permis A'), ('A1', 'Permis A1'), ('B', 'Permis B'), ('C', 'Permis C'), ('D', 'Permis D'), ('E', 'Permis E'), ('OTHER', 'Autre')], default='B', max_length=10)),
                ('mode', models.CharField(choices=[('manual', 'Sélection manuelle'), ('random', 'Tirage aléatoire')], default='random', max_length=10)),
                ('themes', models.JSONField(blank=True, default=list, verbose_name='Thèmes (tirage)')),
                ('difficulties', models.JSONField(blank=True, default=list, verbose_name='Difficultés (tirage)')),
                ('num_questions', models.PositiveIntegerField(default=20)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('points_per_question', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('max_attempts', models.PositiveIntegerField(default=0, verbose_name='Tentatives max (0 = illimité)')),
                ('shuffle', models.BooleanField(default=True)),
                ('show_corrections', models.BooleanField(default=True)),
                ('is_exam', models.BooleanField(default=False, verbose_name='Examen final')),
                ('pass_threshold', models.PositiveSmallIntegerField(default=70, verbose_name='Seuil de réussite (%)')),
                ('is_published', models.BooleanField(default=True)),
                ('questions', models.ManyToManyField(blank=True, related_name='quizzes', to='pedagogy.question')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='schools.school')),
                ('training', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='schools.training')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='attempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='pedagogy.quiz'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='uniq_question_code_per_school'),
        ),
        migrations.AddConstraint(
            model_name='attemptanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='uniq_answer_per_question'),
        ),
    ]
