# Generated by Django 5.2.15 on 2026-09-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='header',
            field=models.JSONField(default=list),
        ),
    ]
