# Generated by Django 5.2.15 on 2026-09-19 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogy', '0002_importjob_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to='pedagogy.quiz'),
        ),
        migrations.AddField(
            model_name='importjob',
            name='update_existing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='importjob',
            name='updated',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
