# Generated by Django 5.2.15 on 2026-09-20 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogy', '0003_importjob_quiz_importjob_update_existing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursematerial',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='course',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='courses/covers/', verbose_name='Image de couverture'),
        ),
        migrations.AddField(
            model_name='course',
            name='summary',
            field=models.CharField(blank=True, max_length=255, verbose_name='Résumé'),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='download_allowed',
            field=models.BooleanField(default=True, verbose_name='Téléchargement autorisé'),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='is_required',
            field=models.BooleanField(default=True, verbose_name='Obligatoire pour la progression'),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='courses/files/'),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='material_type',
            field=models.CharField(choices=[('text', 'Texte'), ('pdf', 'PDF'), ('video', 'Vidéo'), ('audio', 'Audio'), ('image', 'Image'), ('ppt', 'PowerPoint'), ('word', 'Word'), ('excel', 'Excel'), ('link', 'Lien externe'), ('embed', 'Vidéo en ligne (YouTube, Vimeo)'), ('other', 'Autre fichier')], max_length=10),
        ),
        migrations.CreateModel(
            name='MaterialProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='pedagogy.coursematerial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'material'), name='uniq_progress_user_material')],
            },
        ),
    ]
