# Generated by Django 5.2.15 on 2026-09-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogy', '0004_courses_multiformat'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sequential',
            field=models.BooleanField(default=False, help_text="Un contenu obligatoire reste verrouillé pour l'apprenant tant que le contenu obligatoire précédent n'est pas terminé.", verbose_name='Parcours séquentiel obligatoire'),
        ),
    ]
