# Generated by Django 5.2.15 on 2026-09-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogy', '0007_alter_question_category_alter_quiz_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='sequential',
            field=models.BooleanField(default=True, help_text="Un contenu obligatoire reste verrouillé pour l'apprenant tant que le contenu obligatoire précédent n'est pas terminé.", verbose_name='Parcours séquentiel obligatoire'),
        ),
    ]
