# Generated by Django 5.2.15 on 2026-09-20 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0003_alter_payment_method'),
        ('learners', '0002_initial'),
        ('organizations', '0003_quoterequest'),
        ('schools', '0002_alter_plan_options_remove_plan_price_monthly_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audience', models.CharField(max_length=15)),
                ('cohort_ids', models.JSONField(blank=True, default=list)),
                ('extra_seats', models.PositiveIntegerField(default=0)),
                ('seats', models.PositiveIntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'En attente de paiement'), ('paid', 'Payée'), ('failed', 'Échouée'), ('cancelled', 'Annulée')], default='pending', max_length=10)),
                ('method', models.CharField(default='cinetpay', max_length=15)),
                ('payer_phone', models.CharField(blank=True, max_length=30)),
                ('provider_ref', models.CharField(blank=True, db_index=True, max_length=100)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('result_id', models.PositiveIntegerField(blank=True, help_text="Id de l'abonnement activé", null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_order', to='billing.invoice')),
                ('learner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_orders', to='learners.learner')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_orders', to='organizations.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='schools.plan')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_orders', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Actif'), ('expired', 'Expiré'), ('cancelled', 'Annulé'), ('suspended', 'Suspendu')], default='active', max_length=10)),
                ('amount_paid', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('seats', models.PositiveIntegerField(default=0)),
                ('cohorts', models.ManyToManyField(blank=True, related_name='subscriptions', to='organizations.cohort')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='organizations.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_subscriptions', to='schools.plan')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_subscriptions', to='schools.school')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='subscriptions.subscriptionorder')),
            ],
            options={
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='LearnerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Actif'), ('expired', 'Expiré'), ('cancelled', 'Annulé'), ('suspended', 'Suspendu')], default='active', max_length=10)),
                ('amount_paid', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='learners.learner')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learner_subscriptions', to='schools.plan')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_subscriptions', to='schools.school')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='subscriptions.subscriptionorder')),
            ],
            options={
                'ordering': ['-end_date'],
            },
        ),
    ]
