# Generated by Django 5.2.15 on 2026-09-20 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnersubscription',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learnersubscription',
            name='suspension_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='suspension_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subscriptionorder',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='payment_proofs/', verbose_name='Preuve de paiement'),
        ),
        migrations.AddField(
            model_name='subscriptionorder',
            name='proof_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Référence du reçu / virement'),
        ),
    ]
