# Generated by Django 5.2.15 on 2026-09-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='meeting_url',
            field=models.URLField(blank=True, verbose_name='Lien de la classe virtuelle'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='recording_url',
            field=models.URLField(blank=True, verbose_name='Enregistrement (rediffusion)'),
        ),
    ]
