# Generated by Django 5.2.15 on 2026-09-26 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_negotiated_price'),
        ('practice', '0002_lesson_meeting_url_lesson_recording_url'),
        ('schools', '0006_school_covered_zones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('provider', models.CharField(choices=[('zoom', 'Zoom'), ('teams', 'Microsoft Teams'), ('meet', 'Google Meet'), ('jitsi', 'Jitsi'), ('bbb', 'BigBlueButton'), ('other', 'Autre')], default='jitsi', max_length=10)),
                ('join_url', models.URLField(blank=True)),
                ('host_url', models.URLField(blank=True)),
                ('meeting_id', models.CharField(blank=True, max_length=150)),
                ('passcode', models.CharField(blank=True, max_length=50)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('recording_url', models.URLField(blank=True)),
                ('cohort', models.ForeignKey(blank=True, help_text="Vide = ouverte à tous les apprenants de l'auto-école.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virtual_classes', to='organizations.cohort')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virtual_classes', to='practice.instructor')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_classes', to='schools.school')),
            ],
            options={
                'ordering': ['-scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='VirtualClassQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('virtual_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='practice.virtualclass')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='VirtualClassAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_class_attendances', to=settings.AUTH_USER_MODEL)),
                ('virtual_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='practice.virtualclass')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('virtual_class', 'user'), name='uniq_vclass_attendance')],
            },
        ),
    ]
