# Generated by Django 5.2.15 on 2026-09-19 21:49

import apps.exams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=40, unique=True)),
                ('verification_token', models.CharField(default=apps.exams.models._token, max_length=64, unique=True)),
                ('training_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=10)),
                ('score', models.CharField(max_length=20)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('issued_at', models.DateField()),
                ('status', models.CharField(choices=[('valid', 'Valide'), ('revoked', 'Révoqué')], default='valid', max_length=10)),
            ],
            options={
                'ordering': ['-issued_at', '-id'],
            },
        ),
    ]
