# Generated by Django 5.2.15 on 2026-09-19 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('learners', '0001_initial'),
        ('pedagogy', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
            ],
            options={
                'verbose_name': 'Examen',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pedagogy.quiz',),
        ),
        migrations.AddField(
            model_name='certificate',
            name='attempt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='pedagogy.attempt'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='learners.learner'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='schools.school'),
        ),
    ]
