# Generated by Django 5.2.15 on 2026-09-26 11:42

import apps.core.crypto
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learners', '0003_learner_license_obtained_at'),
        ('organizations', '0003_quoterequest'),
        ('schools', '0005_school_multi_agency'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecyclingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('module', 'Module'), ('package', 'Package')], default='module', max_length=10)),
                ('label', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('modules', models.ManyToManyField(blank=True, help_text='Modules inclus (uniquement pour un package).', limit_choices_to={'kind': 'module'}, related_name='packages', to='admissions.recyclingitem')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recycling_items', to='schools.school')),
            ],
            options={
                'ordering': ['kind', 'label'],
            },
        ),
        migrations.CreateModel(
            name='IndividualQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer', models.CharField(choices=[('new_license', 'Nouveau permis de conduire'), ('extension', 'Extension de catégorie'), ('theory_refresh', 'Recyclage théorique'), ('practical_refresh', 'Recyclage pratique')], max_length=20)),
                ('id_document_type', models.CharField(blank=True, choices=[('resident_card', 'Carte de résident'), ('passport', 'Passeport + visa à jour'), ('id_attestation', "Attestation d'identité"), ('other', 'Autre pièce')], max_length=20)),
                ('id_document_no', apps.core.crypto.EncryptedCharField(blank=True, max_length=255)),
                ('id_document_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('residence', models.CharField(blank=True, max_length=255, verbose_name='Lieu de résidence')),
                ('categories_requested', models.JSONField(blank=True, default=list)),
                ('license_no', models.CharField(blank=True, max_length=60, verbose_name='N° de permis existant')),
                ('categories_held', models.JSONField(blank=True, default=list, help_text='Catégories déjà détenues, cochées par le candidat.')),
                ('categories_expiry', models.JSONField(blank=True, default=dict, help_text='{"C": "2027-01-01", ...} déclaré par le candidat (catégories périodiques C/D/E).')),
                ('categories_to_add', models.JSONField(blank=True, default=list, help_text='Catégorie demandée en extension : une seule à la fois (§3.2).')),
                ('status', models.CharField(choices=[('submitted', 'Déposée'), ('correction_requested', 'Correction demandée'), ('rejected', 'Rejetée'), ('approved', 'Recevable'), ('quoted', 'Devis envoyé'), ('accepted', 'Acceptée')], default='submitted', max_length=20)),
                ('reject_reason', models.TextField(blank=True)),
                ('correction_note', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('negotiated_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('quote_pdf', models.FileField(blank=True, null=True, upload_to='individual_quotes/pdf/')),
                ('sent_channel', models.CharField(blank=True, choices=[('email', 'E-mail'), ('whatsapp', 'WhatsApp')], max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, help_text="Collectivité : si renseignée, la saisie de paiement individuel est désactivée (§3.1) : le candidat bénéficie de l'accès complet prévu par la convention.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_quotes', to='organizations.organization')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_quotes', to='schools.school')),
                ('recycling_items', models.ManyToManyField(blank=True, related_name='quotes', to='admissions.recyclingitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecyclingReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(blank=True, max_length=10)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recycling_reminders', to='learners.learner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecyclingReminderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('first_reminder_days', models.PositiveIntegerField(default=30, verbose_name='Premier rappel (jours après obtention du permis)')),
                ('repeat_every_days', models.PositiveIntegerField(default=180, verbose_name='Rappels suivants tous les (jours)')),
                ('channels', models.JSONField(blank=True, default=list, help_text='["email", "whatsapp"]')),
                ('message', models.TextField(blank=True, default='Pensez à vos recyclages théorique et pratique chez Akwaba Auto-École !')),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recycling_reminder_settings', to='schools.school')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
