# Generated by Django 5.2.15 on 2026-09-26 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
        ('pedagogy', '0005_course_sequential'),
    ]

    operations = [
        migrations.AddField(
            model_name='recyclingitem',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Cours associé : donne accès au contenu correspondant selon les modules achetés (§5.3).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recycling_items', to='pedagogy.course'),
        ),
    ]
