# Generated by Django 5.2.15 on 2026-09-19 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('price_monthly', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('max_learners', models.PositiveIntegerField(default=100)),
                ('max_instructors', models.PositiveIntegerField(default=5)),
                ('max_agencies', models.PositiveIntegerField(default=1)),
                ('max_cohorts', models.PositiveIntegerField(default=5)),
                ('storage_mb', models.PositiveIntegerField(default=1024)),
                ('features', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legal_name', models.CharField(max_length=200, verbose_name='Raison sociale')),
                ('commercial_name', models.CharField(blank=True, max_length=200, verbose_name='Nom commercial')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('registration_no', models.CharField(blank=True, max_length=100, verbose_name='RCCM / identifiant')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('manager_name', models.CharField(blank=True, max_length=150, verbose_name='Responsable')),
                ('categories', models.JSONField(blank=True, default=list)),
                ('opening_hours', models.CharField(blank=True, max_length=255, verbose_name='Horaires')),
                ('pass_threshold', models.PositiveSmallIntegerField(default=70, verbose_name='Seuil de réussite (%)')),
                ('payment_rules', models.TextField(blank=True, verbose_name='Règles de paiement')),
                ('exam_rules', models.TextField(blank=True, verbose_name="Règles d'examen")),
                ('certificate_settings', models.JSONField(blank=True, default=dict)),
                ('signatory_name', models.CharField(blank=True, max_length=150, verbose_name='Signataire du certificat')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['legal_name'],
            },
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('manager_name', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencies', to='schools.school')),
            ],
            options={
                'verbose_name_plural': 'agencies',
                'ordering': ['school', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Actif'), ('expired', 'Expiré'), ('suspended', 'Suspendu'), ('pending', 'En attente')], default='active', max_length=12)),
                ('amount_paid', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('auto_renew', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='schools.plan')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='schools.school')),
            ],
            options={
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('A', 'Permis A'), ('A1', 'Permis A1'), ('B', 'Permis B'), ('C', 'Permis C'), ('D', 'Permis D'), ('E', 'Permis E'), ('OTHER', 'Autre')], max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('theory_hours', models.PositiveIntegerField(default=0)),
                ('practical_hours', models.PositiveIntegerField(default=0)),
                ('duration_days', models.PositiveIntegerField(default=30, verbose_name='Durée (jours)')),
                ('program', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('validation_conditions', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='schools.school')),
            ],
            options={
                'ordering': ['school', 'category', 'name'],
            },
        ),
    ]
