# Generated by Django 5.2.15 on 2026-09-20 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['audience', 'sort_order', 'price']},
        ),
        migrations.RemoveField(
            model_name='plan',
            name='price_monthly',
        ),
        migrations.AddField(
            model_name='plan',
            name='audience',
            field=models.CharField(choices=[('individual', 'Particuliers'), ('organization', 'Entreprises & établissements'), ('school', 'Auto-écoles (SaaS)')], default='school', max_length=15),
        ),
        migrations.AddField(
            model_name='plan',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', '1 mois'), ('quarterly', '3 mois'), ('semi_annual', '6 mois'), ('yearly', '12 mois (1 an)'), ('lifetime', 'À vie')], default='monthly', max_length=15),
        ),
        migrations.AddField(
            model_name='plan',
            name='category',
            field=models.CharField(blank=True, max_length=10, verbose_name='Permis concerné (vide = tous)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='currency',
            field=models.CharField(default='XOF', max_length=3),
        ),
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='plan',
            name='extra_beneficiary_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name="Prix d'une place supplémentaire"),
        ),
        migrations.AddField(
            model_name='plan',
            name='included_beneficiaries',
            field=models.PositiveIntegerField(default=0, verbose_name='Places (bénéficiaires) incluses'),
        ),
        migrations.AddField(
            model_name='plan',
            name='includes_courses',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='includes_exams',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='includes_quizzes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Mis en avant'),
        ),
        migrations.AddField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Prix (par période)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='schools.school'),
        ),
        migrations.AddField(
            model_name='plan',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='subscription_required',
            field=models.BooleanField(default=False, verbose_name='Abonnement obligatoire pour accéder aux QCM / examens'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
