# Generated by Django 5.2.15 on 2026-09-20 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_quoterequest'),
        ('schools', '0002_alter_plan_options_remove_plan_price_monthly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='available_from',
            field=models.DateField(blank=True, null=True, verbose_name='Vendu à partir du'),
        ),
        migrations.AddField(
            model_name='plan',
            name='available_until',
            field=models.DateField(blank=True, null=True, verbose_name="Vendu jusqu'au"),
        ),
        migrations.AddField(
            model_name='plan',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dedicated_plans', to='organizations.cohort'),
        ),
        migrations.AddField(
            model_name='plan',
            name='custom_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée personnalisée (jours)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dedicated_plans', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', '1 mois'), ('quarterly', '3 mois'), ('semi_annual', '6 mois'), ('yearly', '12 mois (1 an)'), ('lifetime', 'À vie'), ('custom', 'Durée personnalisée (jours)')], default='monthly', max_length=15),
        ),
    ]
