# Generated by Django 5.2.15 on 2026-09-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_plan_available_from_plan_available_until_plan_cohort_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='exam_min_average',
            field=models.PositiveSmallIntegerField(default=60, verbose_name='Score moyen requis aux QCM pour accéder aux examens blancs (%)'),
        ),
    ]
