# Generated by Django 5.2.15 on 2026-09-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_school_exam_min_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='multi_agency',
            field=models.BooleanField(default=False, verbose_name='Fonctionne avec plusieurs agences (sites)'),
        ),
    ]
