# Generated by Django 5.2.15 on 2026-09-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_school_multi_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='covered_zones',
            field=models.JSONField(blank=True, default=list, help_text='Ex: ["Abidjan"]. Une inscription en ligne dont la zone déclarée n\'y figure pas est refusée (§4.1/§5.1). Vide = aucune restriction.', verbose_name='Zones géographiques couvertes'),
        ),
    ]
