# Generated by Django 5.2.15 on 2026-09-19 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=60)),
                ('category', models.CharField(choices=[('A', 'Permis A'), ('A1', 'Permis A1'), ('B', 'Permis B'), ('C', 'Permis C'), ('D', 'Permis D'), ('E', 'Permis E'), ('OTHER', 'Autre')], default='B', max_length=10)),
                ('beneficiaries_count', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Tarif par bénéficiaire')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('organization_contribution', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Contribution organisation / bénéficiaire')),
                ('installments_count', models.PositiveSmallIntegerField(default=1, verbose_name='Échéances apprenant')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Actif'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='draft', max_length=12)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['cohort', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org_type', models.CharField(choices=[('company', 'Entreprise'), ('university', 'Université'), ('grande_ecole', 'Grande école'), ('school', 'École'), ('administration', 'Administration'), ('ngo', 'ONG'), ('association', 'Association'), ('other', 'Autre')], default='company', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('registration_no', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(default=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('planned', 'Planifiée'), ('running', 'En cours'), ('done', 'Terminée'), ('cancelled', 'Annulée')], default='planned', max_length=12)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cohorts', to='schools.agency')),
            ],
            options={
                'ordering': ['-start_date', 'name'],
            },
        ),
    ]
