# Generated by Django 5.2.15 on 2026-09-19 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('practice', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='cohorts', to='practice.instructor'),
        ),
        migrations.AddField(
            model_name='cohort',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='schools.school'),
        ),
        migrations.AddField(
            model_name='cohort',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cohorts', to='schools.training'),
        ),
        migrations.AddField(
            model_name='contract',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='schools.school'),
        ),
        migrations.AddField(
            model_name='contract',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='schools.training'),
        ),
        migrations.AddField(
            model_name='cohort',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cohorts', to='organizations.contract'),
        ),
        migrations.AddField(
            model_name='group',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='organizations.cohort'),
        ),
        migrations.AddField(
            model_name='group',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='practice.instructor'),
        ),
        migrations.AddField(
            model_name='organization',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='schools.school'),
        ),
        migrations.AddField(
            model_name='contract',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='cohort',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cohorts', to='organizations.organization'),
        ),
    ]
