# Generated by Django 5.2.15 on 2026-09-19 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_name', models.CharField(max_length=150)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('formation_label', models.CharField(max_length=200)),
                ('beneficiaries_count', models.PositiveIntegerField(default=1)),
                ('desired_start_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Nouvelle'), ('contacted', 'Contactée'), ('converted', 'Convertie'), ('rejected', 'Rejetée')], default='new', max_length=12)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
