# Generated by Django 5.2.15 on 2026-09-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_quoterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='negotiated_price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Tarif propre à cette collectivité, appliqué à chaque candidat qui lui est rattaché (ex. INSAAC).', max_digits=12, null=True, verbose_name='Tarif négocié par candidat'),
        ),
    ]
