# Generated by Django 5.2.15 on 2026-09-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_negotiated_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='category',
            field=models.CharField(choices=[('A', 'Permis A'), ('B', 'Permis B'), ('C', 'Permis C'), ('D', 'Permis D'), ('E', 'Permis E'), ('OTHER', 'Autre')], default='B', max_length=10),
        ),
    ]
